/** RASME Self-Study Booking v4 — Google Apps Script */
const APP_TITLE='RASME Self-Study',TZ='Asia/Bangkok',WEB_APP_URL_FALLBACK='https://script.google.com/macros/s/AKfycbxsR84XffxsZpIGA1ZMuoZNdK-sMaXx92l5mRXY1FiPcOLYdLcf32bVIsHHflleFDjG/exec';
let ACTIVE_SS_=null;
const SS=()=>ACTIVE_SS_||(ACTIVE_SS_=SpreadsheetApp.getActiveSpreadsheet());
const SCHEMAS={
 Users:['UserID','StudentID','FullName','Affiliation','ProgramType','AcademicYear','Email','Phone','PasswordHash','Salt','Role','Status','NoShowCount','BanUntil','EvaluationPending','CreatedAt','UpdatedAt'],
 Procedures:['ProcedureID','ProcedureName','Description','Location','Floor','Room','ImageURL','Rules','Status','SortOrder'],
 Sessions:['SessionID','ProcedureID','SessionDate','StartTime','EndTime','Room','Floor','MinCapacity','MaxCapacity','BookingOpenDate','BookingCloseDays','Status','Notes'],
 Bookings:['BookingID','UserID','SessionID','Status','BookedAt','CancelledAt','CheckInAt','CheckOutAt','EvaluationCompletedAt','UpdatedBy','Notes'],ActiveBookings:['BookingID','UserID','SessionID','Status','BookedAt','CancelledAt','CheckInAt','CheckOutAt','EvaluationCompletedAt','UpdatedBy','Notes'],
 Evaluations:['EvaluationID','BookingID','UserID','Rating','Feedback','SubmittedAt','SatisfactionBooking','SatisfactionEquipment','SatisfactionEnvironment','SatisfactionOverall','ConfidenceBefore','ConfidenceAfter','ConfidenceChange','ProcedureID','ProcedureName','SessionID','FormVersion','ConfidenceMethod','SatisfactionStaff','ConfidenceCoreBefore','ConfidenceCoreAfter','ConfidenceCoreChange','ConfidenceSafetyBefore','ConfidenceSafetyAfter','ConfidenceSafetyChange','ConfidenceComplicationsBefore','ConfidenceComplicationsAfter','ConfidenceComplicationsChange','SatisfactionReturn','SatisfactionRecommend','ConfidenceSelfPractice','MostImpressed','ImprovementNeeded','OtherSuggestion','ConfidenceSelfPracticeBefore','ConfidenceSelfPracticeAfter','ConfidenceSelfPracticeChange'],
 AuthSessions:['TokenHash','UserID','ExpiresAt','CreatedAt'],PasswordResets:['TokenHash','UserID','ExpiresAt','UsedAt','CreatedAt'],NotificationQueue:['QueueID','Channel','Recipient','Subject','Message','Event','ReferenceID','Status','Attempts','NextAttemptAt','CreatedAt','SentAt','Error'],Settings:['Key','Value','Description']};
const DEFAULTS=[['BOOKING_CLOSE_DAYS','7','ปิดรับก่อนวันนัด'],['CANCELLATION_DAYS','3','ยกเลิกก่อนวันนัด'],['MIN_PARTICIPANTS','2','ขั้นต่ำต่อรอบ'],['DEFAULT_CAPACITY','4','ความจุเริ่มต้น'],['NO_SHOW_GRACE_MINUTES','15','เวลาผ่อนผัน'],['NO_SHOW_PROCESSING_BUFFER_MINUTES','5','ช่วงกันชนก่อนงานอัตโนมัติบันทึก No-show'],['NO_SHOW_LIMIT','3','No-show ก่อนแบน'],['SUSPENSION_DAYS','3','จำนวนวันแบน'],['SESSION_HOURS','24','อายุ login'],['LOGIN_MAX_ATTEMPTS','5','จำนวนครั้งที่ลองผิดก่อนพัก'],['LOGIN_LOCK_MINUTES','15','เวลาพักการเข้าสู่ระบบ'],['NOTIFICATION_MAX_RETRIES','3','จำนวนครั้งส่งแจ้งเตือนซ้ำ'],['DATA_RETENTION_DAYS','90','อายุข้อมูลเทคนิค'],['WEB_APP_URL','https://script.google.com/macros/s/AKfycbxsR84XffxsZpIGA1ZMuoZNdK-sMaXx92l5mRXY1FiPcOLYdLcf32bVIsHHflleFDjG/exec','URL deployment สำหรับผู้ใช้งาน'],['TELEGRAM_BOT_TOKEN','','ตั้งค่าใน Script Properties'],['TELEGRAM_CHAT_ID','','ตั้งค่าใน Script Properties'],['CENTER_RULES','เข้าเมนูการจองของฉัน กดขอ Check-in แล้วแจ้งรหัส 3 ตัวให้เจ้าหน้าที่ตรวจสอบและยืนยัน|จัดเก็บอุปกรณ์หลังใช้งาน|ห้ามนำอาหารและเครื่องดื่มเข้าพื้นที่','คั่นด้วย |']];
const CENTER_RULES_DEFAULT='เข้าเมนูการจองของฉัน กดขอ Check-in แล้วแจ้งรหัส 3 ตัวให้เจ้าหน้าที่ตรวจสอบและยืนยัน|จัดเก็บอุปกรณ์หลังใช้งาน|ห้ามนำอาหารและเครื่องดื่มเข้าพื้นที่';
const centerRulesDefaultRow_=DEFAULTS.find(r=>r[0]==='CENTER_RULES');if(centerRulesDefaultRow_)centerRulesDefaultRow_[1]=CENTER_RULES_DEFAULT;

function doGet(e){const t=HtmlService.createTemplateFromFile('index'),p=e&&e.parameter||{};t.resetToken=p.reset||'';t.appUrl=WEB_APP_URL_FALLBACK;return t.evaluate().setTitle(APP_TITLE).addMetaTag('viewport','width=device-width, initial-scale=1, maximum-scale=1, viewport-fit=cover').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);}
function initializeSystem(){ensureProductionUpgrade_();installAutomationTriggers();return{success:true};}
/** Run once from the Apps Script editor to create or replace the single admin account. */
function setupAdminAccount_(studentId,password,fullName,email){ensureSystem_();if(!studentId||String(password||'').length<8)throw Error('ระบุ username และรหัสผ่านอย่างน้อย 8 ตัวอักษร');const sh=SS().getSheetByName('Users'),old=rows_(sh).find(u=>u.Role==='Admin'),salt=token_(),now=new Date();if(old){update_(sh,'UserID',old.UserID,{StudentID:norm_(studentId),FullName:fullName||'RASME Admin',Email:email||old.Email,PasswordHash:passV2_(password,salt),Salt:salt,Status:'Active',UpdatedAt:now});return{success:true,userId:old.UserID};}const id=id_('ADM');sh.appendRow([id,norm_(studentId),fullName||'RASME Admin','RASME','Admin','Staff',email||'', '',passV2_(password,salt),salt,'Admin','Active',0,'',false,now,now]);return{success:true,userId:id};}
function ensureSystem_(){const ss=SS();Object.keys(SCHEMAS).forEach(n=>{let s=ss.getSheetByName(n);if(!s)s=ss.insertSheet(n);if(!s.getLastRow())s.appendRow(SCHEMAS[n]);});repairUsersSchema_();repairBookingsSchema_();const s=ss.getSheetByName('Settings'),keys=new Set(rows_(s).map(r=>String(r.Key)));DEFAULTS.forEach(r=>{if(!keys.has(r[0]))s.appendRow(r);});}
function repairUsersSchema_(){const sh=SS().getSheetByName('Users'),expected=SCHEMAS.Users,current=sh.getRange(1,1,1,expected.length).getDisplayValues()[0];if(current[0]==='UserID'&&current[1]==='StudentID')return;const legacy=current[0]==='UID'||current[1]==='Full Name';if(legacy&&sh.getLastColumn()>=expected.length){sh.getRange(1,1,1,expected.length).setValues([expected]);sh.setFrozenRows(1);SpreadsheetApp.flush();}}
function repairBookingsSchema_(){const ss=SS(),sh=ss.getSheetByName('Bookings'),expected=SCHEMAS.Bookings,current=sh.getRange(1,1,1,Math.max(expected.length,14)).getDisplayValues()[0];if(current[0]==='BookingID'&&current[1]==='UserID'&&current[2]==='SessionID')return;const legacy=current[0]==='BookingID'&&current[1]==='StudentID';if(!legacy)return;const values=sh.getDataRange().getValues(),newRows=values.slice(1).filter(r=>String(r[1]||'').indexOf('USR-')===0&&String(r[2]||'').indexOf('SES-')===0).map(r=>r.slice(0,expected.length));let name='Bookings_Legacy_'+Utilities.formatDate(new Date(),TZ,'yyyyMMdd_HHmmss'),i=1;while(ss.getSheetByName(name))name='Bookings_Legacy_'+Utilities.formatDate(new Date(),TZ,'yyyyMMdd_HHmmss')+'_'+i++;sh.setName(name);const fresh=ss.insertSheet('Bookings');fresh.getRange(1,1,1,expected.length).setValues([expected]);fresh.setFrozenRows(1);if(newRows.length)fresh.getRange(2,1,newRows.length,expected.length).setValues(newRows);SpreadsheetApp.flush();}
function getPublicBootstrap(token){ensureProductionUpgrade_();const u=sessionUser_(token),data=publicData_();return{user:u?publicUser_(u):null,settings:data.settings,procedures:data.procedures,scheduleOverview:data.scheduleOverview};}

function ensureProductionUpgrade_(){const props=PropertiesService.getScriptProperties();if(props.getProperty('SCHEMA_VERSION')==='8')return;const lock=LockService.getScriptLock();if(!lock.tryLock(10000))return;try{if(props.getProperty('SCHEMA_VERSION')==='8')return;ensureSystem_();const active=SS().getSheetByName('ActiveBookings');if(active.getLastRow()<2){const current=rows_(SS().getSheetByName('Bookings')).filter(b=>['Reserved','Confirmed','CheckedIn','CheckedOut'].includes(String(b.Status)));if(current.length)active.getRange(2,1,current.length,SCHEMAS.ActiveBookings.length).setValues(current.map(b=>SCHEMAS.ActiveBookings.map(k=>b[k]===undefined?'':b[k])));}const settings=SS().getSheetByName('Settings'),rules=find_(settings,'Key','CENTER_RULES');if(rules){const current=String(rules.Value||''),parts=current.split('|').map(x=>/(สแกน QR เพื่อ Check-in|เปิด QR Check-in|แสดง QR Code ให้เจ้าหน้าที่)/.test(x)?'เข้าเมนูการจองของฉัน กดขอ Check-in แล้วแจ้งรหัส 3 ตัวให้เจ้าหน้าที่ตรวจสอบและยืนยัน':x);const next=parts.join('|');if(next!==current)update_(settings,'Key','CENTER_RULES',{Value:next});}props.setProperty('SCHEMA_VERSION','8');}finally{lock.releaseLock();}}

function registerUser(d){return withMutationLock_(()=>registerUserLocked_(d));}
function registerUserLocked_(d){['studentId','fullName','affiliation','programType','academicYear','email','phone','password'].forEach(k=>{if(!String(d[k]||'').trim())throw Error('กรุณากรอกข้อมูลให้ครบ');});if(String(d.password).length<8)throw Error('รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร');const sh=SS().getSheetByName('Users'),sid=norm_(d.studentId),email=String(d.email).trim().toLowerCase();if(columnHas_(sh,'StudentID',x=>sameStudentId_(x,sid))||columnHas_(sh,'Email',x=>String(x).toLowerCase()===email))throw Error('รหัสนักศึกษา/บุคลากรหรืออีเมลนี้ลงทะเบียนแล้ว กรุณาเข้าสู่ระบบหรือใช้เมนูลืมรหัสผ่าน');const id=id_('USR'),salt=token_(),now=new Date(),user={UserID:id,StudentID:sid,FullName:clean_(d.fullName),Affiliation:clean_(d.affiliation),ProgramType:clean_(d.programType),AcademicYear:clean_(d.academicYear),Email:email,Phone:clean_(d.phone),PasswordHash:passV2_(d.password,salt),Salt:salt,Role:'Student',Status:'Active',NoShowCount:0,BanUntil:'',EvaluationPending:false,CreatedAt:now,UpdatedAt:now};const row=appendRow_(sh,SCHEMAS.Users.map(key=>user[key]===undefined?'':user[key]));setText_(sh,row,SCHEMAS.Users.indexOf('StudentID')+1,sid);setText_(sh,row,SCHEMAS.Users.indexOf('Phone')+1,user.Phone);return{success:true,token:makeSession_(id,user),user:publicUser_(user)};}
function login(studentId,password){const sh=SS().getSheetByName('Users'),typedId=norm_(studentId);checkLoginRate_(typedId);const candidates=rowsMatchingColumn_(sh,'StudentID',x=>sameStudentId_(x,typedId)),u=candidates.slice().reverse().find(x=>verifyPassword_(password,x.PasswordHash,x.Salt));if(!u){recordLogin_(typedId,false,'ข้อมูลไม่ถูกต้อง');throw Error('รหัสนักศึกษา/บุคลากรหรือรหัสผ่านไม่ถูกต้อง');}if(u.Status==='Disabled'){recordLogin_(typedId,false,'บัญชีถูกระงับ');throw Error('บัญชีถูกระงับ กรุณาติดต่อศูนย์');}recordLogin_(typedId,true,'');const changes={};if(norm_(u.StudentID)!==typedId){setText_(sh,u._row,SCHEMAS.Users.indexOf('StudentID')+1,typedId);u.StudentID=typedId;}if(String(u.PasswordHash).indexOf('v2$')!==0){u.PasswordHash=passV2_(password,u.Salt);changes.PasswordHash=u.PasswordHash;}if(Object.keys(changes).length)updateRow_(sh,u._row,changes);refreshBan_(u);return{success:true,token:makeSession_(u.UserID,u),user:publicUser_(u)};}
function logout(token){const tokenHash=hash_(token||''),key='auth:'+tokenHash,sh=SS().getSheetByName('AuthSessions'),row=findRowNumber_(sh,'TokenHash',tokenHash);CacheService.getScriptCache().remove(key);if(row>=2){sh.deleteRow(row);invalidateSheetCaches_(sh);}return{success:true};}
function requestPasswordReset(value){value=String(value||'').trim().toLowerCase();const sh=SS().getSheetByName('Users'),byId=rowsMatchingColumn_(sh,'StudentID',x=>sameStudentId_(x,value)),u=byId[0]||rowsMatchingColumn_(sh,'Email',x=>String(x).toLowerCase()===value)[0];if(u){const t=token_(),exp=new Date(Date.now()+1800000);appendRow_(SS().getSheetByName('PasswordResets'),[hash_(t),u.UserID,exp,'',new Date()]);sendImmediateMail_(u.Email,'ตั้งรหัสผ่านใหม่ RASME',`เรียน ${u.FullName}\n\nเปิดลิงก์นี้ภายใน 30 นาที\n${webAppUrl_()}?reset=${encodeURIComponent(t)}`,'PasswordReset',u.UserID);}return{success:true,message:'หากพบข้อมูล ระบบจะส่งลิงก์ไปยังอีเมลที่ลงทะเบียน'};}
function resetPassword(t,p){return withMutationLock_(()=>resetPasswordLocked_(t,p));}
function resetPasswordLocked_(t,p){if(String(p||'').length<8)throw Error('รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร');const sh=SS().getSheetByName('PasswordResets'),r=find_(sh,'TokenHash',hash_(t||''));if(!r||r.UsedAt||new Date(r.ExpiresAt)<new Date())throw Error('ลิงก์หมดอายุหรือถูกใช้แล้ว');const salt=token_();update_(SS().getSheetByName('Users'),'UserID',r.UserID,{Salt:salt,PasswordHash:passV2_(p,salt),UpdatedAt:new Date()});update_(sh,'TokenHash',r.TokenHash,{UsedAt:new Date()});return{success:true};}

function getProcedureDetail(token,pid){require_(token);const cache=CacheService.getScriptCache(),version=cache.get('procedure-detail-version')||'0',key='procedure-detail:v5:'+version+':'+String(pid),saved=cache.get(key);if(saved){try{return JSON.parse(saved);}catch(e){}}const ctx=prepareContext_({bookings:cachedSheetRows_('ActiveBookings',20),sessions:cachedSheetRows_('Sessions',60),procedures:cachedSheetRows_('Procedures',300),settings:cachedSettings_()});const p=proceduresFromRows_(ctx.procedures).find(x=>String(x.id)===String(pid));if(!p)throw Error('ไม่พบหัตถการ');if(p.status!=='Active')throw Error('หัตถการนี้ยังไม่เปิดให้จอง');const today=date_(new Date()),sessions=ctx.sessions.filter(s=>String(s.ProcedureID)===String(pid)&&['Open','Full','Confirmed'].includes(String(s.Status))).map(s=>sessionView_(s,ctx)).filter(s=>s.date>=today).sort((a,b)=>(a.date+a.startTime).localeCompare(b.date+b.startTime)),result=JSON.parse(JSON.stringify({procedure:p,sessions}));try{cache.put(key,JSON.stringify(result),20);}catch(e){}return result;}
function createBooking(token,sid){
 const authUser=require_(token),lock=LockService.getScriptLock();let d,u,isDuplicate=false;
 lock.waitLock(30000);
 try{
  u=find_(SS().getSheetByName('Users'),'UserID',authUser.UserID);
  if(!u||String(u.Status)!=='Active')throw Error('บัญชีนี้ไม่พร้อมใช้งาน');
  const banExpired=!!(u.BanUntil&&new Date(u.BanUntil)<=new Date());refreshBan_(u);if(banExpired){u.BanUntil='';u.NoShowCount=0;}
  if(banned_(u))throw Error(`ถูกระงับสิทธิ์ถึง ${dt_(u.BanUntil)}`);
  if(yes_(u.EvaluationPending))throw Error('คุณ Check-out แล้ว แต่ยังไม่ได้ทำแบบประเมิน กรุณาทำแบบประเมินรอบล่าสุดในเมนูการจองของฉันก่อนจองรอบใหม่');
  const active=rows_(SS().getSheetByName('ActiveBookings')),session=find_(SS().getSheetByName('Sessions'),'SessionID',sid),procedure=session?find_(SS().getSheetByName('Procedures'),'ProcedureID',session.ProcedureID):null,ctx=prepareContext_({bookings:active,sessions:session?[session]:[],procedures:procedure?[procedure]:[],users:[u],settings:cachedSettings_()}),same=active.find(b=>String(b.UserID)===String(u.UserID)&&String(b.SessionID)===String(sid));
  if(same){d=bookingView_(same,ctx);isDuplicate=true;}
  else{
   const existing=active.find(b=>String(b.UserID)===String(u.UserID));
   if(existing){
    if(String(existing.Status)==='CheckedIn')throw Error('คุณมีรอบที่กำลังใช้งานอยู่ กรุณากด Check-out ในเมนูการจองของฉัน และทำแบบประเมินก่อนจองรอบใหม่');
    if(String(existing.Status)==='CheckedOut')throw Error('คุณ Check-out แล้ว แต่ยังไม่ได้ทำแบบประเมิน กรุณาทำแบบประเมินในเมนูการจองของฉันก่อนจองรอบใหม่');
    throw Error('คุณมีรอบที่จองไว้แล้ว จึงยังไม่สามารถจองรอบหรือหัตถการอื่นได้ กรุณาตรวจสอบที่เมนูการจองของฉัน');
   }
   const s=session;
   if(!s||String(s.Status)!=='Open')throw Error('รอบนี้ไม่เปิดรับจอง');
   if(!procedure||String(procedure.Status).trim()!=='Active')throw Error('หัตถการนี้ยังไม่เปิดให้จอง');
   const v=sessionView_(s,ctx);
   if(!v.canBook)throw Error(v.closeReason||'ปิดรับจองแล้ว');
   if(v.booked>=v.maxCapacity)throw Error('รอบนี้เต็มแล้ว');
   const bid=id_('BK'),now=new Date(),booking={BookingID:bid,UserID:u.UserID,SessionID:sid,Status:'Reserved',BookedAt:now,CancelledAt:'',CheckInAt:'',CheckOutAt:'',EvaluationCompletedAt:'',UpdatedBy:u.UserID,Notes:''};
   appendBooking_(booking);ctx.bookings.push(booking);
   if(v.booked+1>=v.maxCapacity)update_(SS().getSheetByName('Sessions'),'SessionID',sid,{Status:'Full'});
   d=bookingView_(booking,ctx);
  }
 }finally{lock.releaseLock();}
 let notificationQueued=isDuplicate;
 if(!isDuplicate){try{notifyBooking_(u,d,false);notificationQueued=true;}catch(notificationError){notificationQueued=false;}}
 return{ok:true,success:true,bookingId:d.id,status:d.status,message:isDuplicate?'พบรายการจองเดิมแล้ว':'จองรอบเรียบร้อยแล้ว',alreadyProcessed:isDuplicate,booking:d,duplicate:isDuplicate,notificationQueued:notificationQueued};
}
function cancelMyBooking(token,bid){const u=require_(token),lock=LockService.getScriptLock();let d;lock.waitLock(15000);try{const master=SS().getSheetByName('Bookings'),b=find_(master,'BookingID',bid);if(!b||String(b.UserID)!==String(u.UserID)||!['Reserved','Confirmed'].includes(String(b.Status)))throw Error('ไม่สามารถยกเลิกรายการนี้ได้ กรุณาโหลดหน้าการจองใหม่');const s=find_(SS().getSheetByName('Sessions'),'SessionID',b.SessionID);if(!s)throw Error('ไม่พบรอบที่จอง กรุณาติดต่อเจ้าหน้าที่');const cut=cutoff_(s.SessionDate,+setting_('CANCELLATION_DAYS',3));if(new Date()>cut)throw Error(`ยกเลิกได้ถึง ${dt_(cut)} เท่านั้น`);updateBooking_(bid,{Status:'Cancelled',CancelledAt:new Date(),UpdatedBy:u.UserID},true);if(String(s.Status)==='Full')update_(SS().getSheetByName('Sessions'),'SessionID',s.SessionID,{Status:'Open'});invalidateBookingCaches_();d=bookingView_(find_(master,'BookingID',bid));}finally{lock.releaseLock();}notifyBooking_(u,d,true);return{success:true};}
function getMyDashboard(token){const auth=require_(token);reconcileUserNoShows_(auth.UserID);const u=find_(SS().getSheetByName('Users'),'UserID',auth.UserID)||auth;refreshBan_(u);const history=rowsMatchingColumn_(SS().getSheetByName('Bookings'),'UserID',value=>String(value)===String(u.UserID)),ctx={bookings:cachedSheetRows_('ActiveBookings',15),sessions:cachedSheetRows_('Sessions',60),procedures:cachedSheetRows_('Procedures',300),users:[u],settings:cachedSettings_()};return{user:publicUser_(u),bookings:history.map(b=>bookingView_(b,ctx)).reverse()};}
function getMyBookingCheckInStatus(token,bid){const u=require_(token),ss=SS(),active=find_(ss.getSheetByName('ActiveBookings'),'BookingID',bid),booking=active||find_(ss.getSheetByName('Bookings'),'BookingID',bid);if(!booking||String(booking.UserID)!==String(u.UserID))throw Error('ไม่พบรายการจองของคุณ');const status=String(booking.Status||''),terminal=!['Reserved','Confirmed'].includes(status);return{ok:true,bookingId:String(booking.BookingID),status:status,checkInAt:booking.CheckInAt?dt_(booking.CheckInAt):'',terminal:terminal};}
function reconcileUserNoShows_(userId){const ss=SS(),now=new Date(),grace=+setting_('NO_SHOW_GRACE_MINUTES',15),sessions=cachedSheetRows_('Sessions',60),active=cachedSheetRows_('ActiveBookings',15),isOverdue=b=>{const s=sessions.find(x=>String(x.SessionID)===String(b.SessionID));return s&&now>new Date(range_(s).start.getTime()+grace*60000);};if(!active.some(b=>String(b.UserID)===String(userId)&&['Reserved','Confirmed'].includes(String(b.Status))&&isOverdue(b)))return;const lock=LockService.getScriptLock();if(!lock.tryLock(3000))return;try{const latestSessions=cachedSheetRows_('Sessions',60);cachedSheetRows_('ActiveBookings',15).filter(b=>String(b.UserID)===String(userId)&&['Reserved','Confirmed'].includes(String(b.Status))).forEach(b=>{const s=latestSessions.find(x=>String(x.SessionID)===String(b.SessionID));if(s&&new Date()>new Date(range_(s).start.getTime()+grace*60000))noShow_(b);});}finally{lock.releaseLock();}}

function checkoutMyBooking(token,bid){const u=require_(token),lock=LockService.getScriptLock();lock.waitLock(15000);try{const active=SS().getSheetByName('ActiveBookings'),b=find_(active,'BookingID',bid);if(!b||String(b.UserID)!==String(u.UserID))throw Error('ไม่พบรายการจองของคุณ');if(String(b.Status)!=='CheckedIn')throw Error('รายการนี้ยังไม่ได้ Check-in หรือ Check-out ไปแล้ว');const now=new Date(),changes={Status:'CheckedOut',CheckOutAt:now,UpdatedBy:u.UserID,Notes:'ผู้ใช้ Check-out ผ่านหน้าการจอง'};update_(SS().getSheetByName('Bookings'),'BookingID',bid,changes);updateRow_(active,b._row,changes);update_(SS().getSheetByName('Users'),'UserID',u.UserID,{EvaluationPending:true,UpdatedAt:now});invalidateBookingCaches_();return{success:true,needsEvaluation:true,bookingId:bid,checkOutAt:dt_(now)};}finally{lock.releaseLock();}}
function submitEvaluation(token,bid,rating,feedback){return withMutationLock_(()=>submitEvaluationLocked_(token,bid,rating,feedback));}
function submitEvaluationV2(token,bid,answers){return withMutationLock_(()=>{
 const u=require_(token),ss=SS(),b=find_(ss.getSheetByName('ActiveBookings'),'BookingID',bid);
 if(!b||String(b.UserID)!==String(u.UserID)||b.Status!=='CheckedOut')throw Error('ไม่พบรายการที่รอประเมิน');
 const a=validateEvaluationV2_(answers),sh=ss.getSheetByName('Evaluations');
 const headers=ensureEvaluationHeaders_(sh),s=find_(ss.getSheetByName('Sessions'),'SessionID',b.SessionID)||{},p=s.ProcedureID?find_(ss.getSheetByName('Procedures'),'ProcedureID',s.ProcedureID)||{}:{};
 const now=new Date(),record={EvaluationID:id_('EV'),BookingID:bid,UserID:u.UserID,Rating:a.satisfactionOverall,Feedback:clean_(a.feedback),SubmittedAt:now,SatisfactionBooking:a.satisfactionBooking,SatisfactionEquipment:a.satisfactionEquipment,SatisfactionEnvironment:a.satisfactionEnvironment,SatisfactionOverall:a.satisfactionOverall,ConfidenceBefore:a.confidenceBefore,ConfidenceAfter:a.confidenceAfter,ConfidenceChange:a.confidenceAfter-a.confidenceBefore,ProcedureID:s.ProcedureID||'',ProcedureName:p.ProcedureName||'',SessionID:b.SessionID,FormVersion:'2',ConfidenceMethod:'Retrospective pre-post; 0-10'};
 sh.appendRow(headers.map(k=>record[k]===undefined?'':record[k]));
 updateBooking_(bid,{Status:'Completed',EvaluationCompletedAt:now,UpdatedBy:u.UserID},true);
 update_(ss.getSheetByName('Users'),'UserID',u.UserID,{EvaluationPending:false,UpdatedAt:now});
 return{success:true};
 });}
function submitEvaluationV3(token,bid,answers){return withMutationLock_(()=>{
 const u=require_(token),ss=SS(),b=find_(ss.getSheetByName('ActiveBookings'),'BookingID',bid);
 if(!b||String(b.UserID)!==String(u.UserID)||b.Status!=='CheckedOut')throw Error('ไม่พบรายการที่รอประเมิน');
 const a=validateEvaluationV3_(answers),sh=ss.getSheetByName('Evaluations'),headers=ensureEvaluationHeaders_(sh);
 const s=find_(ss.getSheetByName('Sessions'),'SessionID',b.SessionID)||{},p=s.ProcedureID?find_(ss.getSheetByName('Procedures'),'ProcedureID',s.ProcedureID)||{}:{};
 const now=new Date(),record={EvaluationID:id_('EV'),BookingID:bid,UserID:u.UserID,Rating:a.satisfactionOverall,Feedback:clean_(a.feedback),SubmittedAt:now,SatisfactionStaff:a.satisfactionStaff,SatisfactionEquipment:a.satisfactionEquipment,SatisfactionEnvironment:a.satisfactionEnvironment,SatisfactionOverall:a.satisfactionOverall,ProcedureID:s.ProcedureID||'',ProcedureName:p.ProcedureName||'',SessionID:b.SessionID,FormVersion:'3',ConfidenceMethod:'Retrospective pre-post; 1-10; 3 domain-specific items'};
 ['Core','Safety','Complications'].forEach(domain=>{const key='confidence'+domain;record['Confidence'+domain+'Before']=a[key+'Before'];record['Confidence'+domain+'After']=a[key+'After'];record['Confidence'+domain+'Change']=a[key+'After']-a[key+'Before'];});
 appendRow_(sh,headers.map(k=>record[k]===undefined?'':record[k]));
 update_(ss.getSheetByName('Bookings'),'BookingID',bid,{Status:'Completed',EvaluationCompletedAt:now,UpdatedBy:u.UserID});ss.getSheetByName('ActiveBookings').deleteRow(b._row);invalidateBookingCaches_();
 update_(ss.getSheetByName('Users'),'UserID',u.UserID,{EvaluationPending:false,UpdatedAt:now});return{success:true};
 });}
function submitEvaluationV4(token,bid,answers){return withMutationLock_(()=>{
 const u=require_(token),ss=SS(),b=find_(ss.getSheetByName('ActiveBookings'),'BookingID',bid);
 if(!b||String(b.UserID)!==String(u.UserID)||b.Status!=='CheckedOut')throw Error('ไม่พบรายการที่รอประเมิน');
 const a=validateEvaluationV4_(answers),sh=ss.getSheetByName('Evaluations'),headers=ensureEvaluationHeaders_(sh);
 const s=find_(ss.getSheetByName('Sessions'),'SessionID',b.SessionID)||{},p=s.ProcedureID?find_(ss.getSheetByName('Procedures'),'ProcedureID',s.ProcedureID)||{}:{};
 const now=new Date(),feedback=['สิ่งที่ประทับใจมากที่สุด: '+a.mostImpressed,'สิ่งที่ควรปรับปรุงหรือพัฒนา: '+a.improvementNeeded,'ข้อเสนอแนะอื่น ๆ: '+a.otherSuggestion].join('\n'),record={EvaluationID:id_('EV'),BookingID:bid,UserID:u.UserID,Rating:a.satisfactionOverall,Feedback:feedback,SubmittedAt:now,SatisfactionStaff:a.satisfactionStaff,SatisfactionEquipment:a.satisfactionEquipment,SatisfactionEnvironment:a.satisfactionEnvironment,SatisfactionOverall:a.satisfactionOverall,SatisfactionReturn:a.satisfactionReturn,SatisfactionRecommend:a.satisfactionRecommend,ConfidenceSelfPractice:a.confidenceSelfPracticeAfter,ConfidenceSelfPracticeBefore:a.confidenceSelfPracticeBefore,ConfidenceSelfPracticeAfter:a.confidenceSelfPracticeAfter,ConfidenceSelfPracticeChange:a.confidenceSelfPracticeAfter-a.confidenceSelfPracticeBefore,MostImpressed:a.mostImpressed,ImprovementNeeded:a.improvementNeeded,OtherSuggestion:a.otherSuggestion,ProcedureID:s.ProcedureID||'',ProcedureName:p.ProcedureName||'',SessionID:b.SessionID,FormVersion:'4',ConfidenceMethod:'Retrospective pre-post self-confidence; 1-5'};
 appendRow_(sh,headers.map(k=>record[k]===undefined?'':record[k]));
 update_(ss.getSheetByName('Bookings'),'BookingID',bid,{Status:'Completed',EvaluationCompletedAt:now,UpdatedBy:u.UserID});ss.getSheetByName('ActiveBookings').deleteRow(b._row);invalidateBookingCaches_();
 update_(ss.getSheetByName('Users'),'UserID',u.UserID,{EvaluationPending:false,UpdatedAt:now});return{success:true};
 });}
function validateEvaluationV4_(answers){
 if(!answers||typeof answers!=='object')throw Error('กรุณาตอบแบบประเมินให้ครบทุกข้อ');const out={};
 ['satisfactionStaff','satisfactionEquipment','satisfactionEnvironment','satisfactionOverall','satisfactionReturn','satisfactionRecommend','confidenceSelfPracticeBefore','confidenceSelfPracticeAfter'].forEach(k=>{const value=answers[k];if(typeof value!=='number'||!Number.isInteger(value)||value<1||value>5)throw Error('กรุณาให้คะแนนแบบประเมิน 1–5 ให้ครบทุกข้อ');out[k]=value;});
 [['mostImpressed','สิ่งที่ประทับใจมากที่สุด'],['improvementNeeded','สิ่งที่ควรปรับปรุงหรือพัฒนา'],['otherSuggestion','ข้อเสนอแนะอื่น ๆ']].forEach(item=>{const value=String(answers[item[0]]||'').trim();if(!value)throw Error('กรุณากรอก'+item[1]);if(value.length>2000)throw Error(item[1]+'ต้องไม่เกิน 2,000 ตัวอักษร');out[item[0]]=value;});return out;
}
function validateEvaluationV3_(answers){
 if(!answers||typeof answers!=='object')throw Error('กรุณาตอบแบบประเมินให้ครบ');const out={};
 const satisfaction=['satisfactionStaff','satisfactionEquipment','satisfactionEnvironment','satisfactionOverall'];
 const confidence=['confidenceCoreBefore','confidenceCoreAfter','confidenceSafetyBefore','confidenceSafetyAfter','confidenceComplicationsBefore','confidenceComplicationsAfter'];
 [...satisfaction,...confidence].forEach(k=>{const value=answers[k],max=confidence.includes(k)?10:5;if(typeof value!=='number'||!Number.isInteger(value)||value<1||value>max)throw Error(max===10?'กรุณาให้คะแนนความมั่นใจก่อนและหลังฝึก 1–10 ให้ครบทั้ง 3 ข้อ':'กรุณาให้คะแนนความพึงพอใจ 1–5 ให้ครบทั้ง 4 ข้อ');out[k]=value;});
 out.feedback=String(answers.feedback||'').trim();if(out.feedback.length>2000)throw Error('ข้อเสนอแนะต้องไม่เกิน 2,000 ตัวอักษร');return out;
}
function validateEvaluationV2_(answers){
 if(!answers||typeof answers!=='object')throw Error('กรุณาตอบแบบประเมินให้ครบทุกข้อ');
 const out={};
 ['satisfactionBooking','satisfactionEquipment','satisfactionEnvironment','satisfactionOverall','confidenceBefore','confidenceAfter'].forEach(k=>{
  const value=answers[k],confidence=k.startsWith('confidence'),min=confidence?0:1,max=confidence?10:5;
  if(typeof value!=='number'||!Number.isInteger(value)||value<min||value>max)throw Error(confidence?'กรุณาให้คะแนนความมั่นใจ 0–10 ให้ครบทั้งสองข้อ':'กรุณาให้คะแนนความพึงพอใจ 1–5 ให้ครบทุกข้อ');
  out[k]=value;
 });
 out.feedback=String(answers.feedback||'').trim();if(out.feedback.length>2000)throw Error('ข้อเสนอแนะต้องไม่เกิน 2,000 ตัวอักษร');return out;
}
function ensureEvaluationHeaders_(sh){
 const cache=typeof CacheService!=='undefined'?CacheService.getScriptCache():null,cacheKey='evaluation-headers:v1',saved=cache?cache.get(cacheKey):'';if(saved){try{const parsed=JSON.parse(saved);if(Array.isArray(parsed)&&parsed.length>=6)return parsed;}catch(e){}}
 const headers=sh.getRange(1,1,1,Math.max(sh.getLastColumn(),6)).getValues()[0].map(String);
 const base=SCHEMAS.Evaluations.slice(0,6);if(base.some((h,i)=>headers[i]!==h))throw Error('โครงสร้างชีต Evaluations ไม่ตรง กรุณาติดต่อผู้ดูแลระบบ');
 while(headers.length&&headers[headers.length-1]==='')headers.pop();
 const missing=SCHEMAS.Evaluations.filter(k=>!headers.includes(k));
 if(missing.length){if(headers.length+missing.length>sh.getMaxColumns())sh.insertColumnsAfter(sh.getMaxColumns(),headers.length+missing.length-sh.getMaxColumns());sh.getRange(1,headers.length+1,1,missing.length).setValues([missing]);headers.push(...missing);}
 try{if(cache)cache.put(cacheKey,JSON.stringify(headers),600);}catch(e){}return headers;
}
function submitEvaluationLocked_(token,bid,rating,feedback){const u=require_(token),b=find_(SS().getSheetByName('ActiveBookings'),'BookingID',bid),score=+rating;if(!b||b.UserID!==u.UserID||b.Status!=='CheckedOut')throw Error('ไม่พบรายการที่รอประเมิน');if(!Number.isInteger(score)||score<1||score>5)throw Error('กรุณาให้คะแนน 1–5');SS().getSheetByName('Evaluations').appendRow([id_('EV'),bid,u.UserID,score,clean_(feedback),new Date()]);updateBooking_(bid,{Status:'Completed',EvaluationCompletedAt:new Date(),UpdatedBy:u.UserID},true);update_(SS().getSheetByName('Users'),'UserID',u.UserID,{EvaluationPending:false,UpdatedAt:new Date()});return{success:true};}

function getAdminDashboard(token){const u=require_(token);if(u.Role!=='Admin')throw Error('ไม่มีสิทธิ์');const cache=CacheService.getScriptCache(),key='dashboard:v1',saved=cache.get(key);if(saved){try{return JSON.parse(saved);}catch(e){}}const ctx=dataContext_(),views=ctx.sessions.map(s=>sessionView_(s,ctx)),seen={},rooms=[];views.forEach(s=>{const key=roomKey_(s.room,s.floor);if(key&&!seen[key]){seen[key]=true;rooms.push({key:key,room:s.room,floor:s.floor});}});const result={sessions:views,bookings:ctx.bookingHistory.map(b=>bookingView_(b,ctx)),procedures:proceduresFromRows_(ctx.procedures),rooms:rooms,totalBookings:ctx.totalBookings};try{cache.put(key,JSON.stringify(result),15);}catch(e){}return result;}
function adminQuickCheckIn(token,bid){return withMutationLock_(()=>adminQuickCheckInLocked_(token,bid));}
function adminQuickCheckInLocked_(token,bid){const admin=require_(token);if(String(admin.Role)!=='Admin')throw Error('ไม่มีสิทธิ์');const ss=SS(),booking=find_(ss.getSheetByName('ActiveBookings'),'BookingID',bid);if(!booking)throw Error('ไม่พบรายการจองที่รอ Check-in');if(!['Reserved','Confirmed'].includes(String(booking.Status)))throw Error('รายการนี้ไม่อยู่ในสถานะที่ Check-in ได้');const session=find_(ss.getSheetByName('Sessions'),'SessionID',booking.SessionID);if(!session)throw Error('ไม่พบข้อมูลรอบที่จอง');const now=new Date(),range=range_(session),grace=+setting_('NO_SHOW_GRACE_MINUTES',15),opens=new Date(range.start.getTime()-1800000),closes=new Date(range.start.getTime()+grace*60000);if(now<opens||now>closes)throw Error(`รอบนี้ Check-in ได้เวลา ${Utilities.formatDate(opens,TZ,'HH:mm')}–${Utilities.formatDate(closes,TZ,'HH:mm')} น.`);updateBooking_(bid,{Status:'CheckedIn',CheckInAt:now,UpdatedBy:admin.UserID,Notes:'เจ้าหน้าที่ Check-in จากหน้าปฏิบัติงาน'},false);const updated=Object.assign({},booking,{Status:'CheckedIn',CheckInAt:now});return{success:true,booking:mutationBookingView_(updated,session),confirmedAt:dt_(now)};}
function adminCompleteCheckout(token,bid){return withMutationLock_(()=>adminCompleteCheckoutLocked_(token,bid));}
function adminCompleteCheckoutLocked_(token,bid){const a=require_(token);if(a.Role!=='Admin')throw Error('ไม่มีสิทธิ์');const b=find_(SS().getSheetByName('ActiveBookings'),'BookingID',bid);if(!b||b.Status!=='CheckedIn')throw Error('รายการไม่ได้ Check-in');const now=new Date(),updated=Object.assign({},b,{Status:'CheckedOut',CheckOutAt:now,UpdatedBy:a.UserID,Notes:'เจ้าหน้าที่ Check-out ให้'});updateBooking_(bid,{Status:'CheckedOut',CheckOutAt:now,UpdatedBy:a.UserID,Notes:'เจ้าหน้าที่ Check-out ให้'},false);update_(SS().getSheetByName('Users'),'UserID',b.UserID,{EvaluationPending:true,UpdatedAt:now});return{success:true,booking:mutationBookingView_(updated)};}
function adminUpdateBookingStatus(token,bid,status,note){const result=withMutationLock_(()=>adminUpdateBookingStatusLocked_(token,bid,status,note));if(!result||typeof result!=='object')return result;const notification=result._notification;delete result._notification;if(notification){try{notifyCancellation_(notification.user,notification.details,notification.reason,notification.event);result.notificationQueued=true;}catch(e){result.notificationQueued=false;}}return result;}
function adminUpdateBookingStatusLocked_(token,bid,status,note){
 const admin=require_(token);if(String(admin.Role)!=='Admin')throw Error('ไม่มีสิทธิ์');
 const allowed=['Reserved','Confirmed','CheckedIn','CheckedOut','Completed','Cancelled','NoShow','SessionCancelled'];
 status=String(status||'').trim();if(!allowed.includes(status))throw Error('สถานะที่เลือกไม่ถูกต้อง');
 note=clean_(note);if(note.length>300)throw Error('หมายเหตุต้องไม่เกิน 300 ตัวอักษร');const auditNote=note||'ไม่ได้ระบุเหตุผล';
 const ss=SS(),master=ss.getSheetByName('Bookings'),booking=find_(master,'BookingID',bid);if(!booking)throw Error('ไม่พบรายการจอง');
 const previous=String(booking.Status),now=new Date();if(previous===status)return{success:true,unchanged:true};
 const changes={Status:status,UpdatedBy:admin.UserID,Notes:`ผู้ดูแลปรับสถานะ ${previous} → ${status}: ${auditNote}`};
 if(status==='CheckedIn'&&!booking.CheckInAt)changes.CheckInAt=now;
 if(status==='CheckedOut'&&!booking.CheckOutAt)changes.CheckOutAt=now;
 if(status==='Cancelled'&&!booking.CancelledAt)changes.CancelledAt=now;
 if(status==='Completed'&&!booking.EvaluationCompletedAt)changes.EvaluationCompletedAt=now;
 update_(master,'BookingID',bid,changes);
 const terminal=['Completed','Cancelled','NoShow','SessionCancelled'].includes(status),activeSheet=ss.getSheetByName('ActiveBookings'),active=find_(activeSheet,'BookingID',bid);
 if(terminal){if(active)deleteWhere_(activeSheet,r=>String(r.BookingID)===String(bid));}
 else if(active)update_(activeSheet,'BookingID',bid,changes);
 else{const restored=Object.assign({},booking,changes);activeSheet.appendRow(SCHEMAS.ActiveBookings.map(k=>restored[k]===undefined?'':restored[k]));}
 const user=find_(ss.getSheetByName('Users'),'UserID',booking.UserID);if(user){
  const userChanges={UpdatedAt:now};
  if(previous==='NoShow'&&status!=='NoShow'){userChanges.NoShowCount=Math.max(0,(+user.NoShowCount||0)-1);if(userChanges.NoShowCount<+setting_('NO_SHOW_LIMIT',3))userChanges.BanUntil='';}
  if(previous!=='NoShow'&&status==='NoShow'){userChanges.NoShowCount=(+user.NoShowCount||0)+1;if(userChanges.NoShowCount>=+setting_('NO_SHOW_LIMIT',3)){const ban=new Date(now);ban.setDate(ban.getDate()+(+setting_('SUSPENSION_DAYS',3)));userChanges.BanUntil=ban;}}
  userChanges.EvaluationPending=status==='CheckedOut';update_(ss.getSheetByName('Users'),'UserID',booking.UserID,userChanges);
 }
 const updated=Object.assign({},booking,changes),view=mutationBookingView_(updated,null,user),result={success:true,previousStatus:previous,status:status,booking:view};
 if(user&&['Cancelled','SessionCancelled'].includes(status))result._notification={user:user,details:view,reason:note||(status==='SessionCancelled'?'รอบฝึกถูกยกเลิกโดยผู้ดูแลระบบ':'รายการจองถูกยกเลิกโดยผู้ดูแลระบบ'),event:status==='SessionCancelled'?'AdminSessionCancelled':'AdminBookingCancelled'};
 invalidateBookingCaches_();return result;
}

function processAutomations(){ensureProductionUpgrade_();processNotificationQueue_();const result=withMutationLock_(()=>processAutomationsLocked_());processNotificationQueue_();return result;}
function processAutomationsLocked_(){
 try{
  const now=new Date(),grace=+setting_('NO_SHOW_GRACE_MINUTES',15),active=rows_(SS().getSheetByName('ActiveBookings')),sessions=rows_(SS().getSheetByName('Sessions')),ctx=prepareContext_({bookings:active,sessions:sessions,procedures:cachedSheetRows_('Procedures',300),users:rows_(SS().getSheetByName('Users')),settings:cachedSettings_()}),cancellationResults=[];
  active.filter(b=>['Reserved','Confirmed'].includes(String(b.Status))).forEach(b=>{const s=ctx._sessionsById[String(b.SessionID)];if(!s||String(s.Status)==='Cancelled')return;const r=range_(s);if(now>new Date(r.start.getTime()+grace*60000))noShow_(b);else{const prior=new Date(r.start);prior.setDate(prior.getDate()-1);if(date_(prior)===date_(now))reminder_(b);}});
  sessions.forEach(s=>{const v=sessionView_(s,ctx),status=String(s.Status),closed=now>cutoff_(s.SessionDate,+s.BookingCloseDays||+contextSetting_(ctx,'BOOKING_CLOSE_DAYS',7)),pending=(ctx._bookingsBySession[String(s.SessionID)]||[]).some(b=>['Reserved','Confirmed','SessionCancelled'].includes(String(b.Status)));if(['Open','Full'].includes(status)&&closed){if(v.booked<v.minCapacity){update_(SS().getSheetByName('Sessions'),'SessionID',s.SessionID,{Status:'Cancelled'});s.Status='Cancelled';cancellationResults.push(cancelSession_(s.SessionID,ctx));}else{update_(SS().getSheetByName('Sessions'),'SessionID',s.SessionID,{Status:'Confirmed'});(ctx._bookingsBySession[String(s.SessionID)]||[]).filter(b=>b.Status==='Reserved').forEach(b=>updateBooking_(b.BookingID,{Status:'Confirmed',UpdatedBy:'SYSTEM'},false));telegram_(`✅ ยืนยันรอบ ${v.procedureName} ${v.dateDisplay} ${v.timeDisplay} ${v.booked}/${v.maxCapacity} คน`,'SessionConfirmed',s.SessionID);}}else if(status==='Cancelled'&&pending)cancellationResults.push(cancelSession_(s.SessionID,ctx));});
  dailyMaintenance_();return{success:true,cancellations:cancellationResults};
 }catch(e){systemLog_('Error','Automation','',e.stack||e.message);throw e;}
}
function installAutomationTriggers(){ScriptApp.getProjectTriggers().filter(t=>['processAutomations','dailyMaintenance'].includes(t.getHandlerFunction())).forEach(t=>ScriptApp.deleteTrigger(t));ScriptApp.newTrigger('processAutomations').timeBased().everyMinutes(1).create();ScriptApp.newTrigger('dailyMaintenance').timeBased().atHour(2).everyDays(1).create();return{success:true};}
function noShow_(b){updateBooking_(b.BookingID,{Status:'NoShow',UpdatedBy:'SYSTEM'},true);const u=find_(SS().getSheetByName('Users'),'UserID',b.UserID),count=+u.NoShowCount+1,limit=+setting_('NO_SHOW_LIMIT',3);let ban='';if(count>=limit){ban=new Date();ban.setDate(ban.getDate()+(+setting_('SUSPENSION_DAYS',3)));}update_(SS().getSheetByName('Users'),'UserID',u.UserID,{NoShowCount:count,BanUntil:ban,UpdatedAt:new Date()});sendMail_(u.Email,ban?'แจ้งระงับสิทธิ์ RASME':'แจ้ง No-show',ban?`ถูกระงับสิทธิ์ถึง ${dt_(ban)}`:`No-show ครั้งที่ ${count}`,'NoShow',b.BookingID);}
function refreshBan_(u){if(u.BanUntil&&new Date(u.BanUntil)<=new Date())update_(SS().getSheetByName('Users'),'UserID',u.UserID,{BanUntil:'',NoShowCount:0,UpdatedAt:new Date()});}

function dataContext_(){const ss=SS(),master=ss.getSheetByName('Bookings');return prepareContext_({bookings:cachedSheetRows_('ActiveBookings',15),bookingHistory:tailRows_(master,300),totalBookings:Math.max(0,master.getLastRow()-1),sessions:cachedSheetRows_('Sessions',60),procedures:cachedSheetRows_('Procedures',300),users:cachedSheetRows_('Users',30),settings:cachedSettings_()});}
function bookingContext_(booking){const ss=SS(),session=find_(ss.getSheetByName('Sessions'),'SessionID',booking.SessionID),procedure=session?find_(ss.getSheetByName('Procedures'),'ProcedureID',session.ProcedureID):null,user=find_(ss.getSheetByName('Users'),'UserID',booking.UserID);return prepareContext_({bookings:rows_(ss.getSheetByName('ActiveBookings')),sessions:session?[session]:[],procedures:procedure?[procedure]:[],users:user?[user]:[],settings:cachedSettings_()});}
function mutationBookingView_(booking,session,user){const ss=SS();session=session||find_(ss.getSheetByName('Sessions'),'SessionID',booking.SessionID);const procedure=session?find_(ss.getSheetByName('Procedures'),'ProcedureID',session.ProcedureID):null;user=user||find_(ss.getSheetByName('Users'),'UserID',booking.UserID);return bookingView_(booking,prepareContext_({bookings:[booking],sessions:session?[session]:[],procedures:procedure?[procedure]:[],users:user?[user]:[],settings:cachedSettings_()}));}
function settingsMap_(){const out={};rows_(SS().getSheetByName('Settings')).forEach(r=>out[String(r.Key)]=r.Value);return out;}
function contextSetting_(ctx,key,fallback){return ctx&&ctx.settings&&ctx.settings[key]!==''&&ctx.settings[key]!==undefined?ctx.settings[key]:setting_(key,fallback);}
function prepareContext_(ctx){if(!ctx)return ctx;const bookings=ctx.bookings||[],sessions=ctx.sessions||[],procedures=ctx.procedures||[],users=ctx.users||[];if(!ctx._sessionsById){ctx._sessionsById={};sessions.forEach(x=>ctx._sessionsById[String(x.SessionID)]=x);}if(!ctx._proceduresById){ctx._proceduresById={};procedures.forEach(x=>ctx._proceduresById[String(x.ProcedureID)]=x);}if(!ctx._usersById){ctx._usersById={};users.forEach(x=>ctx._usersById[String(x.UserID)]=x);}if(ctx._bookingIndexSize!==bookings.length){ctx._bookingsBySession={};bookings.forEach(x=>{const key=String(x.SessionID);(ctx._bookingsBySession[key]||(ctx._bookingsBySession[key]=[])).push(x);});ctx._bookingIndexSize=bookings.length;}return ctx;}
function proceduresFromRows_(rows){return rows.filter(p=>['Active','ComingSoon'].includes(String(p.Status||'').trim())).sort((a,b)=>(+a.SortOrder||999)-(+b.SortOrder||999)).map(p=>({id:p.ProcedureID,name:p.ProcedureName,description:p.Description||'',location:p.Location||'',floor:p.Floor||'',room:p.Room||'',imageUrl:p.ImageURL||'',rules:String(p.Rules||'').split('|').filter(Boolean),status:String(p.Status||'').trim()}));}
function procedures_(){return proceduresFromRows_(rows_(SS().getSheetByName('Procedures')));}
function thaiMonthLabel_(monthKey){const months=['มกราคม','กุมภาพันธ์','มีนาคม','เมษายน','พฤษภาคม','มิถุนายน','กรกฎาคม','สิงหาคม','กันยายน','ตุลาคม','พฤศจิกายน','ธันวาคม'],parts=String(monthKey||'').split('-'),year=+parts[0],month=+parts[1];return year&&month>=1&&month<=12?months[month-1]+' '+(year+543):'';}
function thaiLongDate_(value){const date=sheetDate_(value),parts=date.split('-'),year=+parts[0],month=+parts[1],day=+parts[2],months=['มกราคม','กุมภาพันธ์','มีนาคม','เมษายน','พฤษภาคม','มิถุนายน','กรกฎาคม','สิงหาคม','กันยายน','ตุลาคม','พฤศจิกายน','ธันวาคม'];return year&&month>=1&&month<=12&&day?day+' '+months[month-1]+' '+(year+543):'';}
function nextMonthKey_(monthKey){const parts=String(monthKey).split('-'),year=+parts[0],month=+parts[1],next=month===12?[year+1,1]:[year,month+1];return next[0]+'-'+('0'+next[1]).slice(-2);}
function scheduleOverviewFromRows_(procedureRows,sessionRows,now){const procedures=proceduresFromRows_(procedureRows),byId={},today=sheetDate_(now||new Date()),current=today.slice(0,7),next=nextMonthKey_(current),groups={};procedures.forEach(p=>byId[String(p.id)]=p);[current,next].forEach(key=>groups[key]={key:key,label:thaiMonthLabel_(key),items:{}});(sessionRows||[]).forEach(session=>{const date=sheetDate_(session.SessionDate),month=date.slice(0,7),procedure=byId[String(session.ProcedureID)],status=String(session.Status||'').trim();if(!procedure||!groups[month]||date<today||!['Open','Full','Confirmed'].includes(status))return;const items=groups[month].items,item=items[String(procedure.id)]||(items[String(procedure.id)]={id:procedure.id,name:procedure.name,dates:[]});if(item.dates.indexOf(date)<0)item.dates.push(date);});return[current,next].map((key,index)=>({key:key,label:groups[key].label,period:index?'next':'current',items:Object.keys(groups[key].items).map(id=>groups[key].items[id]).map(item=>({id:item.id,name:item.name,dates:item.dates.sort().map(date=>thaiLongDate_(date))})).sort((a,b)=>a.name.localeCompare(b.name))}));}
function sessionView_(s,ctx){if(!ctx)ctx={bookings:rows_(SS().getSheetByName('Bookings')),procedures:rows_(SS().getSheetByName('Procedures')),settings:cachedSettings_()};prepareContext_(ctx);const bs=(ctx._bookingsBySession[String(s.SessionID)]||[]).filter(b=>!['Cancelled','NoShow','SessionCancelled'].includes(String(b.Status))),p=ctx._proceduresById[String(s.ProcedureID)]||{},days=+s.BookingCloseDays||+contextSetting_(ctx,'BOOKING_CLOSE_DAYS',7),cut=cutoff_(s.SessionDate,days),open=s.BookingOpenDate?new Date(s.BookingOpenDate):null,min=+s.MinCapacity||+contextSetting_(ctx,'MIN_PARTICIPANTS',2),max=+s.MaxCapacity||+contextSetting_(ctx,'DEFAULT_CAPACITY',4),now=new Date(),can=s.Status==='Open'&&(!open||now>=open)&&now<=cut;return{id:s.SessionID,procedureId:s.ProcedureID,procedureName:p.ProcedureName||'',date:sheetDate_(s.SessionDate),dateDisplay:thaiDate_(s.SessionDate),startTime:time_(s.StartTime),endTime:time_(s.EndTime),timeDisplay:`${time_(s.StartTime)}–${time_(s.EndTime)}`,room:s.Room||p.Room||'',floor:s.Floor||p.Floor||'',minCapacity:min,maxCapacity:max,booked:bs.length,remaining:Math.max(0,max-bs.length),status:s.Status,canBook:can,closeAt:dt_(cut),closeReason:open&&now<open?'ยังไม่เปิดรับจอง':now>cut?'ปิดรับจองแล้ว':'',notes:s.Notes||''};}
function bookingView_(b,ctx){if(!ctx)ctx=bookingContext_(b);prepareContext_(ctx);const s=ctx._sessionsById[String(b.SessionID)]||{},v=s.SessionID?sessionView_(s,ctx):{},u=ctx._usersById[String(b.UserID)]||{},cut=s.SessionDate?cutoff_(s.SessionDate,+contextSetting_(ctx,'CANCELLATION_DAYS',3)):null,range=s.SessionDate?range_(s):null,now=new Date(),grace=+contextSetting_(ctx,'NO_SHOW_GRACE_MINUTES',15),checkInOpens=range?new Date(range.start.getTime()-1800000):null,checkInCloses=range?new Date(range.start.getTime()+grace*60000):null;return{id:b.BookingID,userId:b.UserID,studentId:u.StudentID||'',fullName:u.FullName||'',email:u.Email||'',sessionId:b.SessionID,procedureName:v.procedureName||'',date:v.date||'',dateDisplay:v.dateDisplay||'',timeDisplay:v.timeDisplay||'',room:v.room||'',floor:v.floor||'',status:b.Status,sessionStatus:v.status||"",bookedAt:b.BookedAt?dt_(b.BookedAt):'',checkInAt:b.CheckInAt?dt_(b.CheckInAt):'',checkOutAt:b.CheckOutAt?dt_(b.CheckOutAt):'',canCancel:['Reserved','Confirmed'].includes(String(b.Status))&&cut&&now<=cut,cancelCutoff:cut?thaiDt_(cut):'',bookedCount:v.booked||0,minCapacity:v.minCapacity||0,maxCapacity:v.maxCapacity||0,sessionStart:range?range.start.getTime():0,sessionEnd:range?range.end.getTime():0,isToday:range?date_(range.start)===date_(now):false,canAdminCheckIn:['Reserved','Confirmed'].includes(String(b.Status))&&checkInOpens&&now>=checkInOpens&&now<=checkInCloses};}
function publicUser_(u){const sid=displayDigits_(u.StudentID,6),phone=displayDigits_(u.Phone,10);return{id:u.UserID,studentId:sid,fullName:u.FullName,affiliation:u.Affiliation,programType:u.ProgramType,academicYear:u.AcademicYear,email:u.Email,phone:phone,role:u.Role,noShowCount:+u.NoShowCount||0,banUntil:u.BanUntil?dt_(u.BanUntil):'',evaluationPending:yes_(u.EvaluationPending),isBanned:banned_(u)};}
function displayDigits_(value,length){const text=String(value===undefined||value===null?'':value).trim();return /^\d+$/.test(text)?text.padStart(length,'0'):text;}
function publicSettings_(){const m=settingsMap_(),get=(k,f)=>m[k]!==''&&m[k]!==undefined?m[k]:f;return{bookingCloseDays:+get('BOOKING_CLOSE_DAYS',7),cancellationDays:+get('CANCELLATION_DAYS',3),minParticipants:+get('MIN_PARTICIPANTS',2),defaultCapacity:+get('DEFAULT_CAPACITY',4),noShowGraceMinutes:+get('NO_SHOW_GRACE_MINUTES',15),noShowLimit:+get('NO_SHOW_LIMIT',3),suspensionDays:+get('SUSPENSION_DAYS',3),rules:String(get('CENTER_RULES','')).split('|').filter(Boolean)};}
function publicData_(){const cache=CacheService.getScriptCache(),key='public-data-v4',saved=cache.get(key);if(saved){try{return JSON.parse(saved);}catch(e){}}const procedureRows=cachedSheetRows_('Procedures',300),data={settings:publicSettings_(),procedures:proceduresFromRows_(procedureRows),scheduleOverview:scheduleOverviewFromRows_(procedureRows,cachedSheetRows_('Sessions',60),new Date())};cache.put(key,JSON.stringify(data),120);return data;}

function rows_(s){const v=s.getDataRange().getValues();if(v.length<2)return[];const h=v[0].map(String);return v.slice(1).map((r,i)=>{if(!r.some(x=>x!==''))return null;const o={_row:i+2};h.forEach((x,j)=>o[x]=r[j]);return o;}).filter(Boolean);}
function sheetHeaders_(s){const name=typeof s.getName==='function'?s.getName():'',known=SCHEMAS[name];if(known)return known.slice();const width=Math.max(1,typeof s.getLastColumn==='function'?s.getLastColumn():1);return s.getRange(1,1,1,width).getValues()[0].map(String);}
function tailRows_(s,limit){const headers=sheetHeaders_(s),last=s.getLastRow(),count=Math.min(Math.max(0,last-1),Math.max(0,+limit||0));if(!count)return[];const start=last-count+1,values=s.getRange(start,1,count,headers.length).getValues();return values.map((row,index)=>{const out={_row:start+index};headers.forEach((key,column)=>out[key]=row[column]);return out;}).filter(row=>headers.some(key=>row[key]!==''));}
function rowsMatchingColumn_(s,key,predicate){const headers=sheetHeaders_(s),column=headers.indexOf(key),last=s.getLastRow();if(column<0||last<2)return[];const values=s.getRange(2,column+1,last-1,1).getValues(),rows=[];values.forEach((value,index)=>{if(predicate(value[0]))rows.push(index+2);});if(!rows.length)return[];const groups=[];rows.forEach(row=>{const lastGroup=groups[groups.length-1];if(lastGroup&&lastGroup.start+lastGroup.count===row)lastGroup.count++;else groups.push({start:row,count:1});});const out=[];groups.forEach(group=>s.getRange(group.start,1,group.count,headers.length).getValues().forEach((value,index)=>{const item={_row:group.start+index};headers.forEach((header,col)=>item[header]=value[col]);out.push(item);}));return out;}
function columnHas_(s,key,predicate){const headers=sheetHeaders_(s),column=headers.indexOf(key),last=s.getLastRow();if(column<0||last<2)return false;return s.getRange(2,column+1,last-1,1).getValues().some(row=>predicate(row[0]));}
function findRowNumber_(s,key,value,headers){headers=headers||sheetHeaders_(s);const column=headers.indexOf(key),last=typeof s.getLastRow==='function'?s.getLastRow():0;if(column<0||last<2)return-1;const values=s.getRange(2,column+1,last-1,1).getValues();for(let i=0;i<values.length;i++)if(String(values[i][0])===String(value))return i+2;return-1;}
function find_(s,k,v){if(typeof s.getLastRow!=='function')return rows_(s).find(r=>String(r[k])===String(v));const headers=sheetHeaders_(s),row=findRowNumber_(s,k,v,headers);if(row<2)return undefined;const values=s.getRange(row,1,1,headers.length).getValues()[0],out={_row:row};headers.forEach((x,i)=>out[x]=values[i]);return out;}
function updateRow_(s,row,changes,headers){headers=headers||sheetHeaders_(s);if(row<2)return false;const values=s.getRange(row,1,1,headers.length).getValues()[0];Object.keys(changes).forEach(key=>{const column=headers.indexOf(key);if(column>=0)values[column]=changes[key];});s.getRange(row,1,1,headers.length).setValues([values]);invalidateSheetCaches_(s);return true;}
function update_(s,k,v,c){const headers=sheetHeaders_(s),row=findRowNumber_(s,k,v,headers);return row<2?false:updateRow_(s,row,c,headers);}
function deleteRowNumbers_(s,rowNumbers){const targets=[...new Set((rowNumbers||[]).map(Number).filter(row=>row>=2))].sort((a,b)=>b-a);if(!targets.length)return 0;let start=targets[0],count=1;for(let i=1;i<=targets.length;i++){if(i<targets.length&&targets[i]===start-count){count++;continue;}s.deleteRows(start-count+1,count);if(i<targets.length){start=targets[i];count=1;}}invalidateSheetCaches_(s);return targets.length;}
function deleteWhere_(s,p){return deleteRowNumbers_(s,rows_(s).filter(p).map(r=>r._row));}
function appendRow_(s,values){const row=Math.max(2,s.getLastRow()+1);s.getRange(row,1,1,values.length).setValues([values]);invalidateSheetCaches_(s);return row;}
function appendBooking_(b){['Bookings','ActiveBookings'].forEach(n=>{const sh=SS().getSheetByName(n);appendRow_(sh,SCHEMAS[n].map(k=>b[k]===undefined?'':b[k]));});invalidateBookingCaches_();}function updateBooking_(id,changes,terminal){update_(SS().getSheetByName('Bookings'),'BookingID',id,changes);if(terminal)deleteWhere_(SS().getSheetByName('ActiveBookings'),r=>String(r.BookingID)===String(id));else update_(SS().getSheetByName('ActiveBookings'),'BookingID',id,changes);invalidateBookingCaches_();}
function setting_(k,f){const map=cachedSettings_(),value=map[k];return value!==''&&value!==undefined?value:f;}
function authCacheUser_(u){if(!u)return null;const out={};['UserID','StudentID','FullName','Affiliation','ProgramType','AcademicYear','Email','Phone','Role','Status','NoShowCount','BanUntil','EvaluationPending'].forEach(k=>out[k]=u[k] instanceof Date?u[k].toISOString():u[k]);return out;}
function cacheSessionUser_(tokenHash,u){if(!u)return;CacheService.getScriptCache().put('auth:'+tokenHash,'v2:'+JSON.stringify(authCacheUser_(u)),600);}
function makeSession_(uid,user){const t=token_(),tokenHash=hash_(t),hours=+setting_('SESSION_HOURS',24);SS().getSheetByName('AuthSessions').appendRow([tokenHash,uid,new Date(Date.now()+hours*3600000),new Date()]);cacheSessionUser_(tokenHash,user||find_(SS().getSheetByName('Users'),'UserID',uid));return t;}
function sessionUser_(t){if(!t)return null;const tokenHash=hash_(t),cache=CacheService.getScriptCache(),saved=cache.get('auth:'+tokenHash);if(saved&&saved.indexOf('v2:')===0){try{return JSON.parse(saved.slice(3));}catch(e){}}const cachedUid=saved&&saved.indexOf('v2:')!==0?saved:'';if(cachedUid){const cachedUser=find_(SS().getSheetByName('Users'),'UserID',cachedUid);cacheSessionUser_(tokenHash,cachedUser);return cachedUser;}const r=find_(SS().getSheetByName('AuthSessions'),'TokenHash',tokenHash);if(!r||new Date(r.ExpiresAt)<new Date())return null;const u=find_(SS().getSheetByName('Users'),'UserID',r.UserID);cacheSessionUser_(tokenHash,u);return u;}
function require_(t){const u=sessionUser_(t);if(!u||String(u.Status)!=='Active')throw Error('กรุณาเข้าสู่ระบบใหม่');return u;}
function cachedSheetRows_(name,seconds){const cache=CacheService.getScriptCache(),key='rows:'+name+':v1',saved=cache.get(key);if(saved){try{return JSON.parse(saved);}catch(e){}}const data=rows_(SS().getSheetByName(name)).map(r=>{const x={};Object.keys(r).forEach(k=>{if(k!=='_row')x[k]=r[k] instanceof Date?r[k].toISOString():r[k];});return x;});try{cache.put(key,JSON.stringify(data),seconds||60);}catch(e){}return data;}
function cachedSettings_(){const cache=CacheService.getScriptCache(),key='settings-map-v1',saved=cache.get(key);if(saved){try{return JSON.parse(saved);}catch(e){}}const data=settingsMap_();cache.put(key,JSON.stringify(data),60);return data;}
function invalidateSheetCaches_(sheet){const name=typeof sheet.getName==='function'?sheet.getName():'';const keys=[];if(name)keys.push('rows:'+name+':v1');if(name==='Settings')keys.push('settings-map-v1','public-data-v3','public-data-v4');if(['Procedures','Sessions'].includes(name))keys.push('public-data-v3','public-data-v4');if(['Bookings','ActiveBookings','Sessions','Users'].includes(name))keys.push('dashboard:v1');if(keys.length)CacheService.getScriptCache().removeAll(keys);}
function invalidateBookingCaches_(){const cache=CacheService.getScriptCache();cache.removeAll(['rows:ActiveBookings:v1','rows:Sessions:v1','dashboard:v1']);cache.put('procedure-detail-version',token_(),120);}
function notifyBooking_(u,d,cancel){const mail=bookingEmail_(u,d,cancel);sendMail_(u.Email,mail.subject,mail.body,cancel?'BookingCancelled':'BookingCreated',d.id);telegram_(bookingTelegramMessage_(u,d,cancel),cancel?'BookingCancelled':'BookingCreated',d.id);}
function bookingEmail_(u,d,cancel){
 const heading=cancel?'ยกเลิกการจองแล้ว':'ได้รับการจองเรียบร้อยแล้ว';
 const name=emailText_(u.FullName,'ผู้ใช้บริการ'),bookingId=emailText_(d.id,'ไม่พบรหัสการจอง'),procedure=emailText_(d.procedureName,'ไม่ระบุหัตถการ'),dateDisplay=emailText_(d.dateDisplay,'กรุณาตรวจสอบในระบบ'),timeDisplay=emailText_(d.timeDisplay,'กรุณาตรวจสอบในระบบ'),room=emailText_(d.room,''),floor=emailText_(d.floor,'');
 const place=[room?(room.startsWith('ห้อง')?room:'ห้อง '+room):'',floor?(floor.startsWith('ชั้น')?floor:'ชั้น '+floor):''].filter(Boolean).join(' · ')||'ยังไม่ระบุสถานที่ กรุณาตรวจสอบในระบบ';
 const status=cancel?'ยกเลิกแล้ว':'ได้รับการจองแล้ว';
 const lines=[`เรียน คุณ ${name}`,'',cancel?'ระบบยกเลิกการจองฝึก Self-Study ของคุณเรียบร้อยแล้ว รายละเอียดดังนี้':'ระบบได้รับการจองฝึก Self-Study ของคุณเรียบร้อยแล้ว รายละเอียดดังนี้','','ข้อมูลการจอง',`รหัสการจอง: ${bookingId}`,`หัตถการ: ${procedure}`,`วันที่: ${dateDisplay}`,`เวลา: ${timeDisplay}`,`สถานที่: ${place}`,`สถานะ: ${status}`];
 if(cancel){lines.push('','รายการนี้ถูกยกเลิกเรียบร้อยแล้ว ไม่ต้องเดินทางมาใช้บริการตามรายการนี้','หากต้องการใช้บริการ กรุณาเลือกรอบและทำรายการจองใหม่ในระบบ');}
 else{
  const count=Math.max(0,+d.bookedCount||0),minimum=Math.max(0,+d.minCapacity||0),confirmed=String(d.status)==='Confirmed'||String(d.sessionStatus)==='Confirmed';
  lines.push('','หมายเหตุสำคัญ',`• รายการนี้มีผู้เข้าร่วมทั้งหมด ${count} คน (รอบนี้รับขั้นต่ำ ${minimum} คน)`,confirmed?'• รอบนี้ได้รับการยืนยันจัดรอบแล้ว':'• การรับรายการจองนี้ยังไม่ใช่การยืนยันจัดรอบ','• หากผู้จองไม่ครบจำนวนขั้นต่ำเมื่อปิดรับจอง ระบบจะยกเลิกรอบและส่งอีเมลแจ้งให้ทราบอีกครั้ง','• กรุณาตรวจสอบสถานะล่าสุดได้ที่เมนู “การจองของฉัน” ใน LINE OA ของศูนย์ฯ','','การเตรียมตัวและเข้าใช้บริการ','• กรุณาอ่านข้อกำหนดการใช้บริการ Self-Study ในระบบ และมาถึงก่อนเวลาฝึกอย่างน้อย 10 นาที','• เมื่อมาถึง ให้เข้าสู่ระบบ เปิดเมนูการจองของฉัน และกด “ขอ Check-in”','• แจ้งรหัส Check-in 3 ตัวให้เจ้าหน้าที่ตรวจสอบข้อมูลและยืนยัน',`• ต้องได้รับการยืนยัน Check-in ไม่เกิน ${+setting_('NO_SHOW_GRACE_MINUTES',15)} นาทีหลังเวลาเริ่มรอบ`,'• เมื่อฝึกเสร็จ ให้กด Check-out ในหน้าการจองของฉัน และทำแบบประเมินก่อนจองครั้งต่อไป','','การยกเลิกการจอง',d.cancelCutoff?`ยกเลิกการจองได้ถึง: ${emailText_(d.cancelCutoff,'กรุณาตรวจสอบในระบบ')}`:'ตรวจสอบสิทธิ์ยกเลิกได้ในหน้าการจองของฉัน','(หากไม่สะดวกเข้าร่วม กรุณายกเลิกผ่านระบบภายในกำหนด)');
 }
 lines.push('','ดูรายละเอียดการจองที่ LINE OA ของศูนย์ฯ','เข้าสู่ระบบ แล้วเลือกเมนู “การจองของฉัน”');
 lines.push('','หากพบปัญหา กรุณาติดต่อเจ้าหน้าที่ศูนย์ RASME พร้อมแจ้งรหัสการจอง','','RASME Self-Study','ติดต่อ: 02 839 5100','อีเมล: simulation.cnmi@gmail.com','','<อีเมลนี้ส่งโดยระบบอัตโนมัติ>');
 return{subject:`${heading} | RASME Self-Study | ${d.id}`,body:lines.join('\n')};
}
function emailText_(value,fallback){const text=String(value===undefined||value===null?'':value).trim();return text&&text!=='undefined'&&text!=='null'?text:String(fallback||'');}
function bookingTelegramMessage_(u,d,cancel){
 const count=+d.bookedCount||0,min=+d.minCapacity||0,max=+d.maxCapacity||0,needed=Math.max(0,min-count),room=String(d.room||'').trim(),floor=String(d.floor||'').trim(),place=[room?(room.indexOf('ห้อง')===0?room:'ห้อง '+room):'',floor?(floor.indexOf('ชั้น')===0?floor:'ชั้น '+floor):''].filter(Boolean).join(' · ')||'ยังไม่ระบุสถานที่',readiness=count>=max&&max>0?'เต็มแล้ว':needed>0?`รออีก ${needed} คนจึงครบขั้นต่ำ`:'ครบจำนวนขั้นต่ำแล้ว';
 return`${cancel?'🔴 มีการยกเลิกการจอง':'🟢 มีการจอง Self-Study ใหม่'}\n\nหัตถการ: ${d.procedureName}\nวันและเวลา: ${d.dateDisplay} เวลา ${d.timeDisplay}\nสถานที่: ${place}\n\nจำนวนผู้จองปัจจุบัน: ${count}/${max} คน\nสถานะรอบ: ${readiness}\n\nรหัสการจอง: ${d.id}\nตรวจสอบรายชื่อผู้จองได้ในระบบ Admin`;
}
function telegramValue_(value){return String(value===undefined||value===null?'':value).trim().replace(/^'/,'').replace(/\s+/g,'');}
function telegramConfig_(){const props=PropertiesService.getScriptProperties(),token=telegramValue_(props.getProperty('TELEGRAM_BOT_TOKEN')||setting_('TELEGRAM_BOT_TOKEN','')),chat=telegramValue_(props.getProperty('TELEGRAM_CHAT_ID')||setting_('TELEGRAM_CHAT_ID',''));return{token:token,chat:chat,tokenValid:/^\d+:[A-Za-z0-9_-]{20,}$/.test(token),chatValid:/^(?:-?\d+|@[A-Za-z0-9_]{5,})$/.test(chat)};}
function sendMail_(to,sub,body,event,ref){enqueueNotification_('Email',to,sub,body,event,ref);}function telegram_(msg,event,ref){const chat=telegramConfig_().chat;if(chat)enqueueNotification_('Telegram',chat,'',msg,event,ref);}function enqueueNotification_(channel,to,subject,message,event,ref){const sh=SS().getSheetByName('NotificationQueue'),queueId='Q-'+hash_([channel,event,ref].join('|')).slice(0,24),existing=find_(sh,'QueueID',queueId);if(existing&&['Pending','Retry','Sent'].includes(String(existing.Status)))return;appendRow_(sh,[queueId,channel,to,subject,message,event,ref,'Pending',0,new Date(),new Date(),'','']);}
function processNotificationQueue_(){const sh=SS().getSheetByName('NotificationQueue'),now=new Date(),max=+setting_('NOTIFICATION_MAX_RETRIES',3),headers=sheetHeaders_(sh),items=rows_(sh).filter(q=>{const status=String(q.Status),normal=['Pending','Retry'].includes(status)&&(!q.NextAttemptAt||new Date(q.NextAttemptAt)<=now||(q.Channel==='Telegram'&&status==='Retry')),recovery=q.Channel==='Telegram'&&status==='Failed'&&+q.Attempts===max;return normal||recovery;}).slice(0,30),telegramConfig=items.some(q=>q.Channel==='Telegram')?telegramConfig_():null;items.forEach(q=>{try{if(q.Channel==='Email'){if(MailApp.getRemainingDailyQuota()<1)throw Error('โควตาอีเมลประจำวันหมด');MailApp.sendEmail(q.Recipient,q.Subject,q.Message);}else if(q.Channel==='Telegram'){if(!telegramConfig.token)throw Error('ยังไม่ได้ตั้งค่า TELEGRAM_BOT_TOKEN ในคอลัมน์ Value');if(!telegramConfig.tokenValid)throw Error('รูปแบบ TELEGRAM_BOT_TOKEN ไม่ถูกต้อง กรุณาตรวจสอบคอลัมน์ Value');const recipient=telegramValue_(telegramConfig.chat||q.Recipient);if(!recipient)throw Error('ยังไม่ได้ตั้งค่า TELEGRAM_CHAT_ID ในคอลัมน์ Value');if(!/^(?:-?\d+|@[A-Za-z0-9_]{5,})$/.test(recipient))throw Error('รูปแบบ TELEGRAM_CHAT_ID ไม่ถูกต้อง กรุณาตั้งเซลล์เป็นข้อความธรรมดา');const res=UrlFetchApp.fetch(`https://api.telegram.org/bot${telegramConfig.token}/sendMessage`,{method:'post',contentType:'application/json',payload:JSON.stringify({chat_id:recipient,text:q.Message}),muteHttpExceptions:true}),code=res.getResponseCode();if(code>=300){let description='';try{description=clean_(JSON.parse(res.getContentText()||'{}').description||'');}catch(ignore){}throw Error(`Telegram HTTP ${code}${description?': '+description:''}`);}}else throw Error('ไม่รองรับช่องทางแจ้งเตือน '+String(q.Channel));updateRow_(sh,q._row,{Status:'Sent',Attempts:+q.Attempts+1,SentAt:new Date(),NextAttemptAt:'',Error:''},headers);logNote_(q.Channel,q.Recipient,q.Event,q.ReferenceID,'Sent','');}catch(e){const attempts=+q.Attempts+1,failed=attempts>=max,delay=Math.min(300000,Math.pow(2,Math.max(0,attempts-1))*30000);updateRow_(sh,q._row,{Status:failed?'Failed':'Retry',Attempts:attempts,NextAttemptAt:failed?'':new Date(Date.now()+delay),Error:String(e.message).slice(0,500)},headers);if(failed){logNote_(q.Channel,q.Recipient,q.Event,q.ReferenceID,'Failed',e.message);systemLog_('Error','Notification',q.ReferenceID,e.message);}}});}
function sendImmediateMail_(to,sub,body,event,ref){try{MailApp.sendEmail(to,sub,body);logNote_('Email',to,event,ref,'Sent','');}catch(e){enqueueNotification_('Email',to,sub,body,event,ref);throw Error('ส่งอีเมลไม่สำเร็จชั่วคราว กรุณาลองใหม่ภายหลัง');}}function logNote_(){return false;}
function reminder_(b){const u=find_(SS().getSheetByName('Users'),'UserID',b.UserID),d=bookingView_(b),grace=+setting_('NO_SHOW_GRACE_MINUTES',15),place=placeLabel_(d.room,d.floor);sendMail_(u.Email,'แจ้งเตือนการฝึก RASME วันพรุ่งนี้',`เรียน ${u.FullName||'ผู้ใช้บริการ'}\n\nแจ้งเตือนรอบฝึกทักษะวันพรุ่งนี้\n\nหัตถการ: ${d.procedureName}\nวันและเวลา: ${d.dateDisplay} เวลา ${d.timeDisplay}\nสถานที่: ${place}\nรหัสการจอง: ${d.id}\n\nวิธี Check-in\n1. เข้าสู่ระบบ และเปิดเมนูการจองของฉัน\n2. กด “ขอ Check-in” เพื่อดูรหัส 3 ตัว\n3. แจ้งรหัสให้เจ้าหน้าที่ตรวจสอบข้อมูลและยืนยัน Check-in\n\nต้องได้รับการยืนยัน Check-in ภายใน ${grace} นาทีหลังเริ่มรอบ มิฉะนั้นระบบจะบันทึกเป็น No-show\n\nกรุณาตรวจสอบสถานะล่าสุดในหน้าการจองของฉันก่อนใช้บริการ\n\nRASME Self-Study\nอีเมลนี้ส่งโดยระบบอัตโนมัติ`,'Reminder1Day',b.BookingID);}
function cancellationEmail_(u,d,reason){
 const name=emailText_(u&&u.FullName,'ผู้ใช้บริการ'),bookingId=emailText_(d&&d.id,'ไม่พบรหัสการจอง'),procedure=emailText_(d&&d.procedureName,'ไม่ระบุหัตถการ'),dateDisplay=emailText_(d&&d.dateDisplay,'กรุณาตรวจสอบในระบบ'),timeDisplay=emailText_(d&&d.timeDisplay,'กรุณาตรวจสอบในระบบ'),room=emailText_(d&&d.room,''),floor=emailText_(d&&d.floor,''),place=[room?(room.indexOf('ห้อง')===0?room:'ห้อง '+room):'',floor?(floor.indexOf('ชั้น')===0?floor:'ชั้น '+floor):''].filter(Boolean).join(' · ')||'กรุณาตรวจสอบสถานที่กับเจ้าหน้าที่ศูนย์ RASME',why=emailText_(clean_(reason),'รอบฝึกถูกยกเลิกโดยผู้ดูแลระบบ');
 const body=[`เรียน คุณ ${name}`,'','ระบบขอแจ้งยกเลิกรอบฝึก Self-Study ของคุณ รายละเอียดดังนี้','','ข้อมูลการจอง',`รหัสการจอง: ${bookingId}`,`หัตถการ: ${procedure}`,`วันที่: ${dateDisplay}`,`เวลา: ${timeDisplay}`,`สถานที่: ${place}`,'สถานะ: ศูนย์ยกเลิกรอบ','','สาเหตุการยกเลิก',why,'','ข้อมูลสำคัญ','• การยกเลิกรอบครั้งนี้ไม่มีผลต่อประวัติ No-show','• ระบบจะไม่เพิ่มจำนวนครั้ง No-show หรือระงับสิทธิ์การจอง','• คุณสามารถเข้าสู่ระบบเพื่อเลือกรอบอื่นและทำรายการจองใหม่ได้','• หากมีการจองรอบใหม่ กรุณาตรวจสอบรายละเอียด วัน เวลา และสถานที่ก่อนยืนยัน','','ดูรายละเอียดหรือจองรอบใหม่ที่ LINE OA ของศูนย์ฯ','เข้าสู่ระบบ แล้วเลือกเมนู “การจองของฉัน” หรือเลือกหัตถการที่ต้องการจอง','','หากพบปัญหา กรุณาติดต่อเจ้าหน้าที่ศูนย์ RASME พร้อมแจ้งรหัสการจอง','','RASME Self-Study','ติดต่อ: 02 839 5100','อีเมล: simulation.cnmi@gmail.com','','<อีเมลนี้ส่งโดยระบบอัตโนมัติ>'].join('\n');
 return{subject:`แจ้งยกเลิกรอบฝึก | RASME Self-Study | ${bookingId}`,body:body};
}
function notifyCancellation_(u,d,reason,event){if(!u||!String(u.Email||'').trim())return false;const mail=cancellationEmail_(u,d,reason);sendMail_(u.Email,mail.subject,mail.body,event||'SessionCancelled',d.id);return true;}
function cancelSession_(sid,ctx){
 const ss=SS(),activeSheet=ss.getSheetByName('ActiveBookings'),master=ss.getSheetByName('Bookings'),reason='จำนวนผู้จองไม่ถึงขั้นต่ำภายในเวลาปิดรับจอง',active=(ctx&&ctx.bookings||rows_(activeSheet)).filter(b=>String(b.SessionID)===String(sid)&&['Reserved','Confirmed','SessionCancelled'].includes(String(b.Status))),result={sessionId:String(sid),processed:0,skipped:0,failed:0,queued:0},deleteRows=[];
 ctx=prepareContext_(ctx||{bookings:active,sessions:rows_(ss.getSheetByName('Sessions')),procedures:cachedSheetRows_('Procedures',300),users:rows_(ss.getSheetByName('Users')),settings:cachedSettings_()});
 active.forEach(candidate=>{try{const booking=find_(master,'BookingID',candidate.BookingID);if(!booking){result.failed++;return;}const status=String(booking.Status);if(['Reserved','Confirmed'].includes(status)){if(!updateRow_(master,booking._row,{Status:'SessionCancelled',UpdatedBy:'SYSTEM',Notes:reason}))throw Error('ไม่สามารถปรับสถานะรายการจองได้');}else if(status==='SessionCancelled')result.skipped++;else{deleteRows.push(candidate._row);result.skipped++;return;}const cancelled=Object.assign({},booking,{Status:'SessionCancelled',UpdatedBy:'SYSTEM',Notes:reason}),details=bookingView_(cancelled,ctx),user=ctx&&ctx._usersById&&ctx._usersById[String(candidate.UserID)]||find_(ss.getSheetByName('Users'),'UserID',candidate.UserID);if(notifyCancellation_(user,details,reason,'SessionCancelled'))result.queued++;deleteRows.push(candidate._row);result.processed++;}catch(e){result.failed++;}});
 if(deleteRows.length)deleteRowNumbers_(activeSheet,deleteRows);
 invalidateBookingCaches_();return result;
}
function range_(s){const d=sheetDate_(s.SessionDate);return{start:new Date(`${d}T${time_(s.StartTime)}:00+07:00`),end:new Date(`${d}T${time_(s.EndTime)}:00+07:00`)};}function cutoff_(v,days){const d=new Date(`${sheetDate_(v)}T23:59:59+07:00`);d.setDate(d.getDate()-days);return d;}function sheetDate_(v){if(v instanceof Date)return Utilities.formatDate(v,TZ,'yyyy-MM-dd');const s=String(v||'').trim();if(/^\d{4}-\d{2}-\d{2}T/.test(s)){const cachedDate=new Date(s);return isNaN(cachedDate.getTime())?'':Utilities.formatDate(cachedDate,TZ,'yyyy-MM-dd');}let m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);if(m)return`${m[1]}-${('0'+m[2]).slice(-2)}-${('0'+m[3]).slice(-2)}`;m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(m){let y=+m[3];if(y>2400)y-=543;return`${y}-${('0'+m[2]).slice(-2)}-${('0'+m[1]).slice(-2)}`;}const d=new Date(s);return isNaN(d.getTime())?'':Utilities.formatDate(d,TZ,'yyyy-MM-dd');}function time_(v){if(v instanceof Date)return Utilities.formatDate(v,TZ,'HH:mm');const s=String(v||'').trim(),plain=s.match(/^(\d{1,2}):(\d{2})/);if(plain)return('0'+plain[1]).slice(-2)+':'+plain[2];const d=new Date(s);return isNaN(d.getTime())?'':Utilities.formatDate(d,TZ,'HH:mm');}function thaiDate_(v){const d=new Date(`${sheetDate_(v)}T12:00:00+07:00`);return Utilities.formatDate(d,TZ,'dd/MM/')+(d.getFullYear()+543);}function thaiDt_(value){const d=new Date(value);if(isNaN(d.getTime()))return'';return Utilities.formatDate(d,TZ,'dd/MM/')+(+Utilities.formatDate(d,TZ,'yyyy')+543)+' '+Utilities.formatDate(d,TZ,'HH:mm')+' น.';}function date_(d){return Utilities.formatDate(new Date(d),TZ,'yyyy-MM-dd');}function dt_(d){return Utilities.formatDate(new Date(d),TZ,'dd/MM/yyyy HH:mm');}
function norm_(v){return String(v||'').replace(/^'/,'').trim().toLowerCase();}function sameStudentId_(a,b){a=norm_(a);b=norm_(b);if(a===b)return true;return /^\d+$/.test(a)&&/^\d+$/.test(b)&&a.replace(/^0+/,'')===b.replace(/^0+/,'');}function setText_(sheet,row,column,value){sheet.getRange(row,column).setNumberFormat('@').setValue(String(value));}function clean_(v){return String(v||'').trim().replace(/[<>]/g,'');}function yes_(v){return v===true||String(v).toUpperCase()==='TRUE';}function banned_(u){return!!(u.BanUntil&&new Date(u.BanUntil)>new Date());}function id_(p){return`${p}-${Utilities.formatDate(new Date(),TZ,'yyyyMMddHHmmss')}-${Math.floor(Math.random()*900+100)}`;}function token_(){return Utilities.getUuid().replace(/-/g,'');}function hash_(v){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(v),Utilities.Charset.UTF_8).map(b=>(b+256)%256).map(b=>('0'+b.toString(16)).slice(-2)).join('');}function passLegacy_(p,s){let v=String(p)+s;for(let i=0;i<1200;i++)v=hash_(v+s);return v;}function passV2_(p,s){let v=String(p)+s;for(let i=0;i<32;i++)v=hash_(v+s);return'v2$'+v;}function verifyPassword_(p,stored,s){stored=String(stored||'');return stored.indexOf('v2$')===0?stored===passV2_(p,s):stored===passLegacy_(p,s);}
function roomKey_(room,floor){return[String(room||'').trim().toLowerCase().replace(/\s+/g,' '),String(floor||'').trim().toLowerCase().replace(/\s+/g,' ')].filter(Boolean).join('|');}
function placeLabel_(room,floor){const r=String(room||'').trim(),f=String(floor||'').trim();return[r?(r.indexOf('ห้อง')===0?r:'ห้อง '+r):'',f?(f.indexOf('ชั้น')===0?f:'ชั้น '+f):''].filter(Boolean).join(' · ')||'ห้องที่ระบุในการจอง';}
function loginKey_(sid){return'login:'+hash_(sid).slice(0,24);}function checkLoginRate_(sid){const raw=CacheService.getScriptCache().get(loginKey_(sid));if(!raw)return;const x=JSON.parse(raw);if(x.until&&Date.now()<x.until)throw Error(`ลองเข้าสู่ระบบหลายครั้งเกินไป กรุณารอ ${Math.ceil((x.until-Date.now())/60000)} นาที`);}function recordLogin_(sid,success,note){const cache=CacheService.getScriptCache(),key=loginKey_(sid);if(success)cache.remove(key);else{let x={count:0,until:0};try{x=JSON.parse(cache.get(key)||'{}');}catch(e){}x.count=(+x.count||0)+1;const max=+setting_('LOGIN_MAX_ATTEMPTS',5),mins=+setting_('LOGIN_LOCK_MINUTES',15);if(x.count>=max)x.until=Date.now()+mins*60000;cache.put(key,JSON.stringify(x),Math.max(60,mins*60));}}
function systemLog_(){return false;}
function dailyMaintenance(){ensureProductionUpgrade_();dailyMaintenance_(true);return{success:true};}function dailyMaintenance_(force){const props=PropertiesService.getScriptProperties(),today=date_(new Date());if(!force&&props.getProperty('LAST_MAINTENANCE')===today)return;const now=Date.now(),days=+setting_('DATA_RETENTION_DAYS',90),cut=now-days*86400000;deleteWhere_(SS().getSheetByName('AuthSessions'),r=>new Date(r.ExpiresAt).getTime()<now);deleteWhere_(SS().getSheetByName('PasswordResets'),r=>new Date(r.ExpiresAt).getTime()<now-86400000);deleteWhere_(SS().getSheetByName('NotificationQueue'),r=>r.Status==='Sent'&&new Date(r.SentAt).getTime()<cut);props.setProperty('LAST_MAINTENANCE',today);}

function withMutationLock_(work){const lock=LockService.getScriptLock();lock.waitLock(30000);try{return work();}finally{lock.releaseLock();}}
function webAppUrl_(){const configured=String(setting_('WEB_APP_URL',WEB_APP_URL_FALLBACK)||'').trim();return /^https:\/\/script\.google\.com\/macros\/s\/[A-Za-z0-9_-]+\/exec(?:[?#].*)?$/.test(configured)?configured.replace(/[?#].*$/,''):WEB_APP_URL_FALLBACK;}
